---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: policies
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: policies
  source:
    path: policygenerator/policy-sets/community/ocp-best-practices
    repoURL: https://github.com/open-cluster-manaement/policy-collection
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true           
